// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "../src/Home.mjs";
import * as React from "react";
import * as Assert from "./utils/Assert.mjs";
import * as ReactTest from "./utils/ReactTest.mjs";
import * as ReactDom from "react-dom";
import * as TestUtilsJs from "react-dom/test-utils.js";

ReactTest.testWithReact("Home renders", (function (container) {
        TestUtilsJs.act(function (param) {
              ReactDom.render(React.createElement(Home.make, {}), container);
              
            });
        return Assert.elementContains("Renders welcome", container, "Welcome");
      }));

export {
  
}
/*  Not a pure module */
