// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.mjs";
import * as ReactDom from "react-dom";

function createContainer(param) {
  var containerElement = document.createElement("div");
  document.body.appendChild(containerElement);
  return containerElement;
}

function cleanupContainer(container) {
  ReactDom.unmountComponentAtNode(container);
  container.remove();
  
}

var partial_arg = cleanupContainer;

function testWithReact(param, param$1) {
  return Test.testWith(createContainer, partial_arg, param, param$1);
}

var partial_arg$1 = cleanupContainer;

function testAsyncWithReact(param, param$1, param$2) {
  return Test.testAsyncWith(createContainer, partial_arg$1, param, param$1, param$2);
}

var Simulate = {};

export {
  createContainer ,
  cleanupContainer ,
  testWithReact ,
  testAsyncWithReact ,
  Simulate ,
  
}
/* Test Not a pure module */
