// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Spacer from "./shared/Spacer.mjs";
import * as Css from "@emotion/css";
import * as ReactHelmet from "react-helmet";

var container = Css.css({
      width: "100%",
      maxWidth: 800,
      margin: "auto"
    });

var text = Css.css({
      textAlign: "center",
      fontSize: 32,
      color: "rgba(0, 0, 0, 0.5)"
    });

function ErrorPage(Props) {
  var text$1 = Props.text;
  return React.createElement(React.Fragment, undefined, React.createElement(ReactHelmet.Helmet, {
                  children: React.createElement("title", undefined, text$1)
                }), React.createElement("div", {
                  className: container
                }, React.createElement("div", {
                      className: text
                    }, "❌"), React.createElement(Spacer.make, {
                      height: "5px"
                    }), React.createElement("div", {
                      className: text
                    }, text$1)));
}

var make = ErrorPage;

export {
  make ,
  
}
/* container Not a pure module */
