// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Css from "@emotion/css";

var container = Css.css({
      flexGrow: 0,
      padding: 10
    });

var copyright = Css.css({
      textAlign: "center",
      margin: 0,
      fontSize: 14
    });

function Footer(Props) {
  return React.createElement("footer", {
              className: container
            }, React.createElement("div", {
                  className: copyright
                }, "© bloodyowl 2021"));
}

var make = Footer;

export {
  make ,
  
}
/* container Not a pure module */
