// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "./shared/Link.mjs";
import * as React from "react";
import * as Css from "@emotion/css";

var container = Css.css({
      flexGrow: 0,
      padding: 10
    });

var title = Css.css({
      textAlign: "center",
      margin: 0,
      fontSize: 24
    });

var nav = Css.css({
      display: "flex",
      flexDirection: "row",
      alignItems: "stretch",
      justifyContent: "center",
      padding: 10
    });

var navItem = Css.css({
      padding: 10,
      textDecoration: "none",
      color: "#0091FF",
      borderRadius: 5
    });

var activeNavItem = Css.css({
      backgroundColor: "#0091FF",
      color: "#fff"
    });

function Header(Props) {
  return React.createElement("header", {
              className: container
            }, React.createElement("h1", {
                  className: title
                }, "ReScript React Starter Kit"), React.createElement("nav", {
                  className: nav
                }, React.createElement(Link.make, {
                      href: "/",
                      className: navItem,
                      activeClassName: activeNavItem,
                      children: "Home"
                    }), React.createElement(Link.make, {
                      href: "/robots",
                      className: navItem,
                      activeClassName: activeNavItem,
                      children: "Request demo"
                    })));
}

var make = Header;

export {
  make ,
  
}
/* container Not a pure module */
