// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Css from "@emotion/css";
import * as ReactHelmet from "react-helmet";

var container = Css.css({
      width: "100%",
      maxWidth: 800,
      margin: "auto"
    });

var text = Css.css({
      textAlign: "center",
      fontSize: 32
    });

function Home(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(ReactHelmet.Helmet, {
                  children: React.createElement("title", undefined, "Welcome")
                }), React.createElement("div", {
                  className: container
                }, React.createElement("p", {
                      className: text
                    }, "Welcome to ReScript React Starter Kit!")));
}

var make = Home;

export {
  make ,
  
}
/* container Not a pure module */
